---
title: "Chaffinches"
author: "Rob Hyman"
date: "04/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```

```{r packages}
library(tidyverse)
library(bookdown)
```

# Introduction
This is the introduction to chaffinches.

# Methods
These are the methods for weighing and sexing the chaffinches.

# Results
############ data import #############
```{r}
file <-  "raw-data/chaff.txt"
write.table(chaff, 
            file, 
            quote = FALSE,
            row.names = FALSE)
```

############# tidy data ############
```{r}
#tidy data
chaff2<- chaff%>% 
  pivot_longer(names_to = "sex", 
               values_to = "mass",
               cols = everything())
view(chaff2)

```

############ create a function ################
```{r}
#sum squared function made
sum_sq <- function(df, measure) {
  df %>% summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}
sum_sq(chaff2, mass)
```
####### adopt function to calculate SS(x) for each group ####
```{r}
sum_sq2 <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq2(chaff2, mass, sex)
```
########### summarising data ##############
```{r}
datasum <- chaff2 %>%
  group_by(sex) %>%
  summarise(mean = mean(mass),
            std = sd(mass),
            n = length(mass),
            se = std/sqrt(n))
datasum
```


# Discussion